### ISSUE TITLE
noindex, nofollow, and follow

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/hugo-theme-iris#259]
## Post

```yaml
robots:
  noindex: true
  nofollow: true
  noarchive: true
```

## Posts Page

```html
<meta name="robots" content="noindex,nofollow,noarchive">
```
