### ISSUE TITLE
hugo 0.108.0 can set wrapStandAloneImageWithinParagraph to false

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/hugo-theme-iris#595]
## Is your feature request related to a problem? Please describe.

https://github.com/gohugoio/hugo/releases/tag/v0.108.0

## Describe the solution you'd like

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
```
